config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :admins
  devise_for :doctors
  devise_for :users

  resources :categories
  resources :appointments
  resources :users do
    member do
      get :profile
      get :view_doctors
      get :make_appointment
      get :view_recommendation
      get :appointments
    end
  end
  resources :doctors, only: [:show] do
    member do
      get :appointments
    end
  end

  patch "doctors/:id", to: "doctors#update"
  get '/doctors', to: 'doctors#index'
  get '/doctors/:id/appointments', to: 'doctors#appointments', as: :doctor_appointments
  get '/doctors/:doctor_id/appointments/:id', to: 'appointments#show', as: :doctor_appointment
  patch '/doctors/:doctor_id/appointments/:id', to: 'appointments#update', as: :doctor_appointment_update
  get '/categories/:id/doctors', to: 'categories#doctors', as: :category_doctors

  get "/home", to: "application#home"

  root to: "application#home"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :phone, uniqueness: true

  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
  # validate :appointment_date_is_in_the_future

  private

  def appointment_date_is_in_the_future
    if appointment.date_time.present? && appointment.date_time < Date.today
      errors.add(:appointment_date, "must be in the future")
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :doctors

  validates :name, uniqueness: true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_and_belongs_to_many :categories
  has_many :appointments
  has_many :users, through: :appointments
  accepts_nested_attributes_for :categories

  validates :name, uniqueness: true
  validates :phone, uniqueness: true

  PHONE_NUMBER_REGEX = /\A\d{5,10}\z/

  validates :phone, format: { with: PHONE_NUMBER_REGEX }

  validate :validate_open_records_count

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def validate_open_records_count
    if open_records_count > 10
      errors.add(:open_records_count, "cannot be greater than 10")
    end
  end
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  belongs_to :appointment
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true
  validates :phone, uniqueness: true

  has_many :appointments
  has_many :doctors, through: :appointments

  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def home
    render "/home"
  end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
    @appointments = current_user.appointments
  end

  def show
    @appointment = Appointment.find(params[:id])
    @doctor = @appointment.doctor
  end

  def create
    @appointment = Appointment.new(appointment_params)
    @appointment.user_id = current_user.id
    if @appointment.save
      redirect_to appointments_path, notice: "Appointment created successfully."
    else
      render :make_appointment
    end
  end

  def update
    @appointment = Appointment.find(params[:id])
    if @appointment.update(appointment_params)
      redirect_to doctor_appointment_path(@appointment.doctor, @appointment)
    else
      render :show
    end
  end

  private

  def appointment_params
    params.require(:appointment).permit(:doctor_id, :user_id, :date_time, :recommendation)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def index
    @categories = Category.all
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice: "Category was successfully created."
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to categories_path, notice: "Category was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path, notice: "Category was successfully deleted."
  end

  private

  def category_params
    params.require(:category).permit(:name, doctor_ids: [])
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :authenticate_doctor!
  before_action :set_appointment, only: [:update]
  before_action :set_doctor, only: [:show, :appointments, :update]

  def appointments
    @appointments = @doctor.appointments
  end

  def show
  end

  def index
    if params[:category_id].present?
      @doctors = Doctor.joins(:categories).where(categories: { id: params[:category_id] })
    else
      @doctors = Doctor.all
    end
  end

  def update
    if params[:appointment].present?
      if @appointment.update(appointment_params)
        redirect_to doctor_appointments_path(@doctor)
      else
        render :appointments
      end
    end
  end

  private

  def set_doctor
    @doctor = Doctor.find(params[:id])
  end

  def set_appointment
    @appointment = @doctor.appointments.find(params[:id])
  end

  def appointment_params
    params.require(:appointment).permit(:recommendation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :view_doctors, :make_appointment, :view_recommendation]

  def show
    @user = User.find(params[:id])
  end

  def view_doctors
    if params[:category_id].present?
      @doctors = Doctor.joins(:categories).where(categories: { id: params[:category_id] })
    else
      @doctors = Doctor.all
    end
  end

  def make_appointment
    @appointment = Appointment.new
  end

  def view_recommendation
    @appointment = Appointment.find(params[:appointment_id])
    @recommendation = @appointment.recommendation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/appointments/index.html.erb
<h1>My Appointments</h1>

<table>
<tr>
  <th>Doctor</th>
  <th>Date/Time</th>
  <th>Recommendation</th>
</tr>
<% @appointments.each do |appointment| %>
  <tr>
    <td><%= appointment.doctor.name %></td>
    <td><%= appointment.date_time.strftime("%B %d, %Y at %I:%M %p") %></td>
    <td><%= appointment.recommendation %></td>
  </tr>
<% end %>
</table>

app/views/appointments/show.html.erb
<%#= form_with model: [@doctor, @appointment], url: appointments_path do |f| %>
  <%#= f.text_area :recommendation, placeholder: "Enter recommendation here..." %>
  <%#= f.submit "Save Recommendation" %>
<%# end %>

<%#= form_for [@doctor, @appointment], url: appointment_path(appointment), method: :patch do |f| %>
  <%#= f.text_area :recommendation, placeholder: "Enter recommendation here..." %>
  <%#= f.submit "Save Recommendation" %>
<%# end %>

<%= @appointment.recommendation %>

<%= form_for @appointment, url: doctor_appointment_path(@doctor, @appointment), method: :patch do |f| %>
  <%= f.text_area :recommendation, placeholder: "Enter recommendation here..." %>
  <%= f.submit "Save Recommendation" %>
<% end %>

app/views/categories/create.html.erb
<%= form_with(model: @category, url: categories_path, method: :post) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :doctor_id, "Assign Doctor" %>
  <%= form.collection_select :doctor_id, Doctor.all, :id, :name, prompt: "Select a doctor" %>

  <%= form.submit "Create Category" %>
<% end %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td><%= link_to 'Edit', edit_category_path(category) %></td>
      <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<%= form_with(model: @category, url: categories_path, method: :post) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :doctor_id, "Assign Doctor" %>
  <%= form.collection_check_boxes :doctor_ids, Doctor.all, :id, :name, prompt: "Select a doctor" %>

  <%= form.submit "Create Category" %>
<% end %>

app/views/doctors/appointments.html.erb
<h1>Appointments for Dr. <%= current_doctor.name %></h1>

<table>
  <tr>
    <th>Patient</th>
    <th>Patient name </th>
    <th>Date/Time</th>
    <th>Recommendation</th>
  </tr>
  <% @appointments.each do |appointment| %>
    <tr>
      <td><%= link_to appointment.user.id, doctor_appointment_path(current_doctor, appointment) %></td>
      <td><%= appointment.user.name %></td>
      <td><%= appointment.date_time %></td>
      <%# if appointment.recommendation.present? %>
        <td><%= appointment&.recommendation %></td>
      <%# end %>
    </tr>
  <% end %>
</table>

app/views/doctors/index.html.erb
<%#= form_tag doctors_path, method: :get do %>
  <%#= select_tag :category_id, options_from_collection_for_select(Category.all, :id, :name) %>
  <%#= submit_tag "Filter" %>
<%# end %>

app/views/doctors/show.html.erb
<h1><%= @doctor.name %> </h1>

<%= form_for @doctor, url: doctor_path(@doctor) do |f| %>
  <%= f.label :categories %>
  <%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClinicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <header>
    <nav>
      <% if current_user.present? || current_doctor.present? %>
        <%= link_to "Home", root_path %> |
        <% if current_user.present? %>
          <%= link_to "My Appointments", appointments_path %> |
          <%= link_to 'View Profile', user_path(current_user) %> |
          <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete } %> |
          <span><%= current_user.name %></span>
    <% elsif current_doctor.present? %>
          <%= link_to "View appointments", doctor_appointments_path(current_doctor) %> |
          <%= link_to "Categories", categories_path %> |
          <%= link_to "Sign out", destroy_doctor_session_path, data: { turbo_method: :delete } %> |
          <span><%= current_doctor.name %></span>
    <% end %>
      <% else %>
        <%= link_to "Home", root_path %> |
        <%= link_to "Login", new_session_path(:user) %> |
        <%= link_to "Sign Up", new_user_registration_path, data: { turbo_frame: "_top" } %>
      <% end %>
    </nav>
  </header>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/make_appointment.html.erb
<h1>Make Appointment</h1>

<%#= form_for @appointment do |f| %>
  <%#= f.label :doctor_id, "Doctor" %>
  <%#= f.collection_select :doctor_id, Doctor.all, :id, :name %>
  <%#= f.label :appointment_date, "Date" %>
  <%#= f.date_field :appointment_date %>
  <%#= f.submit "Make Appointment" %>
<%# end %>

appointments
<%= form_with model: @appointment, url: appointment_path do |form| %>
  <%= form.label :doctor_id, "Select a doctor:" %>
  <%= form.collection_select :doctor_id, Doctor.all, :id, :name, {}, {class: "form-control"} %>
  <%= form.label :date_time, "Select a date and time:" %>
  <%= form.datetime_select :date_time, {}, {class: "form-control"} %>
  <%= form.submit "Make Appointment", class: "btn btn-primary" %>
<% end %>

app/views/users/show.html.erb
<h1>User Profile</h1>

<p>Name: <%= @user.name %></p>
<p>Phone: <%= @user.phone %></p>


<%= form_with model: @appointment = Appointment.new, url: appointments_path do |form| %>
  <%= form.label :doctor_id, "Select a doctor:" %>
  <%= form.collection_select :doctor_id, Doctor.all, :id, :name, {}, {class: "form-control"} %>
  <%= form.label :date_time, "Select a date and time:" %>
  <%= form.datetime_select :date_time, {}, {class: "form-control"} %>
  <%= form.submit "Make Appointment", class: "btn btn-primary" %>
<% end %>

<%= link_to 'View Doctors with categories', view_doctors_user_path(@user) %>
<%#= link_to 'Make Appointment', make_appointment_user_path(@user) %>

app/views/users/view_doctors.html.erb
<%= form_tag view_doctors_user_path(current_user), method: :get do %>
  <%= select_tag :category_id, options_for_select(Category.all.collect { |c| [c.name, c.id] }) %>
  <%= submit_tag "Filter by category" %>
<% end %>

<% @doctors.each do |doctor| %>
  <%= doctor.name %>
<% end %>